seed: 2023

data:
  n_fold: 5
  root: <absolute path>/HIC/data
  # <graph>
  # RG_macro, RG_sub
  # IMDBBINARY, IMDBMULTI, MUTAG, NCI1, PROTEINS
  # <hypergraph>
  # RHG_3, RHG_10, RHG_table, RHG_pyramid
  # IMDB_dir_form, IMDB_dir_genre
  # IMDB_wri_form, IMDB_wri_genre
  # IMDB_dir_genre_m, IMDB_wri_genre_m
  # stream_player, twitter_friend
  name: RHG_10
  degree_as_tag: true

model:
  # graphlet_sampling, graph_subtree
  # hypergraph_rooted, hypergraph_directed_line, 
  # hypergraph_subtree, hypergraph_hyedge
  name: hypergraph_subtree
  normalize: true

hydra:
  run:
    dir: cache/${data.name}__${model.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
